name: Create Pem File

on:
  workflow_call:
    inputs:
      OCI_CLI_KEY_CONTENT:
        required: true
      TF_VAR_private_key_path:
        required: true

jobs:
  PEM_File:
    runs-on: ubuntu-latest
    steps:
      - uses: DamianReeves/write-file-action@master
        name: Script for key
        with:
          path: /tmp/script.sh
          contents: |
            #!/bin/bash
            echo "${{ inputs.OCI_CLI_KEY_CONTENT }}";
      - name: Create PEM file
        shell: bash
        run: |
          chmod +x /tmp/script.sh && mkdir /home/runner/.ssh
          touch ${{ inputs.TF_VAR_private_key_path }}
          /tmp/script.sh > ${{ inputs.TF_VAR_private_key_path }}    
